LANGUAGES = {
    "ru": {
        "name": "Русский",
        "choose_language": "🌐 Выберите язык:",
        "language_changed": "✅ Язык изменён на Русский",
        "welcome": (
            "👋 <b>Привет, {name}!</b>\n\n"
            "<b>Я бот для скачивания видео без водяных знаков.</b>\n\n"
            "Просто отправь мне ссылку на видео из:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "Я скачаю видео и/или аудио для тебя!"
        ),
        "unknown_link": "❌ Я не узнал эту ссылку.\nПожалуйста, отправь ссылку на видео из TikTok, YouTube, Instagram или Pinterest.",
        "recognizing": "🔗 Распознаю видео... Подожди секунду",
        "video_info_error": "❌ Не удалось получить информацию о видео. Проверь ссылку.",
        "unknown_duration": "неизвестно",
        "what_to_download": "Что скачать?",
        "video_btn": "🎬 Видео",
        "audio_btn": "🎵 Аудио",
        "both_btn": "📦 Видео + Аудио",
        "link_not_found": "❌ Ссылка не найдена. Отправь её снова.",
        "starting_download": "⏳ Начинаю скачивание... Это может занять несколько секунд",
        "downloading_video": "📥 Скачиваю видео...",
        "downloading_audio": "📥 Скачиваю аудио...",
        "sending_video": "📤 Отправляю видео...",
        "sending_audio": "📤 Отправляю аудио...",
        "video_ready": "✅ Видео готово!",
        "audio_ready": "✅ Аудио готово!",
        "video_failed": "❌ Не удалось скачать видео.",
        "audio_failed": "❌ Не удалось извлечь аудио.",
        "video_too_large": "❌ Видео слишком большое (>50MB). Telegram не даёт отправлять такие файлы.",
        "audio_too_large": "❌ Аудио слишком большое (>50MB).",
        "error_occurred": "❌ Произошла ошибка при скачивании. Попробуй другую ссылку.",
        "change_language_btn": "🌐 Язык",
        "menu_title": "🏠 <b>Главное меню</b>\n\nВыберите действие:",
        "menu_download_video": "📥 Скачать видео",
        "menu_profile": "👤 Личный кабинет",
        "menu_language": "🌐 Язык",
        "send_link_prompt": "📥 <b>Отправьте ссылку на видео</b>\n\nСсылки из TikTok, YouTube, Instagram или Pinterest — я скачаю видео без водяного знака.",
        "profile_title": "👤 <b>Личный кабинет</b>",
        "profile_user_id": "🆔 ID",
        "profile_name": "👤 Имя",
        "profile_registered": "📅 Зарегистрирован",
        "profile_subscription": "⭐ Подписка",
        "profile_sub_free": "Бесплатная",
        "profile_sub_premium": "💎 Премиум",
        "profile_sub_until": "Действует до",
        "profile_sub_none": "Нет",
        "profile_downloads": "📊 Всего скачиваний",
        "profile_balance": "💰 Баланс",
        "back_btn": "🔙 Назад",
        "premium_feature": "⭐ <b>Это премиум-функция</b>\n\nДоступно только для подписчиков Premium. Оформи подписку, чтобы получить безлимитные скачивания, приоритетную обработку и другие преимущества!",
        "daily_remaining": "Осталось скачиваний: {n}/5",
        "daily_limit_reached": "❌ Дневной лимит исчерпан.\n\nБесплатно можно скачать 5 файлов в день. Лимит обновляется каждый день в 00:00 UTC.\n\n⭐ <b>Купи Premium</b> для безлимитных скачиваний!",
        "caption_video": "🎬 Видео загружено через @videoloadtt_bot",
        "caption_audio": "🎵 Аудио загружено через @videoloadtt_bot",
    },
    "uk": {
        "name": "Українська",
        "choose_language": "🌐 Оберіть мову:",
        "language_changed": "✅ Мову змінено на Українську",
        "welcome": (
            "👋 <b>Привіт, {name}!</b>\n\n"
            "<b>Я бот для завантаження відео без водяних знаків.</b>\n\n"
            "Просто надішли мені посилання на відео з:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "Я завантажу відео та/або аудіо для тебе!"
        ),
        "unknown_link": "❌ Я не впізнав це посилання.\nБудь ласка, надішли посилання на відео з TikTok, YouTube, Instagram або Pinterest.",
        "recognizing": "🔗 Розпізнаю відео... Зачекай секунду",
        "video_info_error": "❌ Не вдалося отримати інформацію про відео. Перевір посилання.",
        "unknown_duration": "невідомо",
        "what_to_download": "Що завантажити?",
        "video_btn": "🎬 Відео",
        "audio_btn": "🎵 Аудіо",
        "both_btn": "📦 Відео + Аудіо",
        "link_not_found": "❌ Посилання не знайдено. Надішли його знову.",
        "starting_download": "⏳ Починаю завантаження... Це може зайняти кілька секунд",
        "downloading_video": "📥 Завантажую відео...",
        "downloading_audio": "📥 Завантажую аудіо...",
        "sending_video": "📤 Відправляю відео...",
        "sending_audio": "📤 Відправляю аудіо...",
        "video_ready": "✅ Відео готове!",
        "audio_ready": "✅ Аудіо готове!",
        "video_failed": "❌ Не вдалося завантажити відео.",
        "audio_failed": "❌ Не вдалося витягти аудіо.",
        "video_too_large": "❌ Відео занадто велике (>50MB). Telegram не дозволяє надсилати такі файли.",
        "audio_too_large": "❌ Аудіо занадто велике (>50MB).",
        "error_occurred": "❌ Сталася помилка при завантаженні. Спробуй інше посилання.",
        "change_language_btn": "🌐 Мова",
        "menu_title": "🏠 <b>Головне меню</b>\n\nОберіть дію:",
        "menu_download_video": "📥 Завантажити відео",
        "menu_profile": "👤 Особистий кабінет",
        "menu_language": "🌐 Мова",
        "send_link_prompt": "📥 <b>Надішліть посилання на відео</b>\n\nПосилання з TikTok, YouTube або Instagram — я завантажу відео без водяного знака.",
        "profile_title": "👤 <b>Особистий кабінет</b>",
        "profile_user_id": "🆔 ID",
        "profile_name": "👤 Ім'я",
        "profile_registered": "📅 Зареєстрований",
        "profile_subscription": "⭐ Підписка",
        "profile_sub_free": "Безкоштовна",
        "profile_sub_premium": "💎 Преміум",
        "profile_sub_until": "Діє до",
        "profile_sub_none": "Немає",
        "profile_downloads": "📊 Всього завантажень",
        "profile_balance": "💰 Баланс",
        "back_btn": "🔙 Назад",
        "premium_feature": "⭐ <b>Це преміум-функція</b>\n\nДоступно тільки для підписників Premium. Оформи підписку, щоб отримати безлімітні завантаження, пріоритетну обробку та інші переваги!",
        "daily_remaining": "Залишилось завантажень: {n}/5",
        "daily_limit_reached": "❌ Денний ліміт вичерпано.\n\nБезкоштовно можна завантажити 5 файлів на день. Ліміт оновлюється щодня о 00:00 UTC.\n\n⭐ <b>Купи Premium</b> для безлімітних завантажень!",
        "caption_video": "🎬 Відео завантажено через @videoloadtt_bot",
        "caption_audio": "🎵 Аудіо завантажено через @videoloadtt_bot",
    },
    "kz": {
        "name": "Қазақша",
        "choose_language": "🌐 Тілді таңдаңыз:",
        "language_changed": "✅ Тіл Қазақшаға ауыстырылды",
        "welcome": (
            "👋 <b>Сәлем, {name}! Мен су таңбасыз бейне жүктейтін ботпын.</b>\n\n"
            "Маған жай ғана сілтеме жібер:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "Мен саған бейне және/немесе аудио жүктеп беремін!"
        ),
        "unknown_link": "❌ Мен бұл сілтемені танымадым.\nTikTok, YouTube немесе Instagram-ға сілтеме жіберіңіз.",
        "recognizing": "🔗 Бейнені танимын... Бір секунд күте тұр",
        "video_info_error": "❌ Бейне ақпаратын алу мүмкін емес. Сілтемені тексеріңіз.",
        "unknown_duration": "белгісіз",
        "what_to_download": "Не жүктеу керек?",
        "video_btn": "🎬 Бейне",
        "audio_btn": "🎵 Аудио",
        "both_btn": "📦 Бейне + Аудио",
        "link_not_found": "❌ Сілтеме табылмады. Оны қайта жіберіңіз.",
        "starting_download": "⏳ Жүктеуді бастаймын... Бірнеше секунд кетуі мүмкін",
        "downloading_video": "📥 Бейнені жүктеп жатырмын...",
        "downloading_audio": "📥 Аудионы жүктеп жатырмын...",
        "sending_video": "📤 Бейнені жіберіп жатырмын...",
        "sending_audio": "📤 Аудионы жіберіп жатырмын...",
        "video_ready": "✅ Бейне дайын!",
        "audio_ready": "✅ Аудио дайын!",
        "video_failed": "❌ Бейнені жүктеу мүмкін емес.",
        "audio_failed": "❌ Аудионы алу мүмкін емес.",
        "video_too_large": "❌ Бейне тым үлкен (>50MB). Telegram мұндай файлдарды жіберуге рұқсат бермейді.",
        "audio_too_large": "❌ Аудио тым үлкен (>50MB).",
        "error_occurred": "❌ Жүктеу кезінде қате пайда болды. Басқа сілтемені сынап көріңіз.",
        "change_language_btn": "🌐 Тіл",
        "menu_title": "🏠 <b>Бас мәзір</b>\n\nӘрекетті таңдаңыз:",
        "menu_download_video": "📥 Бейне жүктеу",
        "menu_profile": "👤 Жеке кабинет",
        "menu_language": "🌐 Тіл",
        "send_link_prompt": "📥 <b>Бейнеге сілтеме жіберіңіз</b>\n\nTikTok, YouTube немесе Instagram сілтемелері — мен су таңбасыз бейне жүктеймін.",
        "profile_title": "👤 <b>Жеке кабинет</b>",
        "profile_user_id": "🆔 ID",
        "profile_name": "👤 Аты",
        "profile_registered": "📅 Тіркелген",
        "profile_subscription": "⭐ Жазылым",
        "profile_sub_free": "Тегін",
        "profile_sub_premium": "💎 Премиум",
        "profile_sub_until": "Мерзімі",
        "profile_sub_none": "Жоқ",
        "profile_downloads": "📊 Барлық жүктеулер",
        "profile_balance": "💰 Баланс",
        "back_btn": "🔙 Артқа",
        "premium_feature": "⭐ <b>Бұл премиум-функция</b>\n\nТек Premium жазылымшыларына қолжетімді. Шексіз жүктеулер, басым өңдеу және басқа артықшылықтар алу үшін жазылымды рәсімдеңіз!",
        "daily_remaining": "Қалған жүктеулер: {n}/5",
        "daily_limit_reached": "❌ Күндік лимит бітті.\n\nКүніне 5 файлды тегін жүктеуге болады. Лимит күн сайын сағат 00:00 UTC-де жаңартылады.\n\n⭐ <b>Premium сатып алыңыз</b> шексіз жүктеу үшін!",
        "caption_video": "🎬 Бейне @videoloadtt_bot арқылы жүктелді",
        "caption_audio": "🎵 Аудио @videoloadtt_bot арқылы жүктелді",
    },
    "tj": {
        "name": "Тоҷикӣ",
        "choose_language": "🌐 Забонро интихоб кунед:",
        "language_changed": "✅ Забон ба Тоҷикӣ иваз карда шуд",
        "welcome": (
            "👋 <b>Салом, {name}! Ман боти боргирии видео бе аломати обӣ ҳастам.</b>\n\n"
            "Танҳо ба ман истинод фиристед:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "Ман барои шумо видео ва/ё аудио бор мекунам!"
        ),
        "unknown_link": "❌ Ман ин истинодро нашинохтам.\nЛутфан истинод ба видео аз TikTok, YouTube ё Instagram фиристед.",
        "recognizing": "🔗 Видеоро шинохта истодаам... Як сония интизор шавед",
        "video_info_error": "❌ Гирифтани маълумот дар бораи видео муяссар нашуд. Истинодро санҷед.",
        "unknown_duration": "номуайян",
        "what_to_download": "Чӣ бор кардан?",
        "video_btn": "🎬 Видео",
        "audio_btn": "🎵 Аудио",
        "both_btn": "📦 Видео + Аудио",
        "link_not_found": "❌ Истинод ёфт нашуд. Онро аз нав фиристед.",
        "starting_download": "⏳ Боргириро оғоз мекунам... Якчанд сония тӯл мекашад",
        "downloading_video": "📥 Видеоро бор мекунам...",
        "downloading_audio": "📥 Аудиоро бор мекунам...",
        "sending_video": "📤 Видеоро мефиристам...",
        "sending_audio": "📤 Аудиоро мефиристам...",
        "video_ready": "✅ Видео тайёр!",
        "audio_ready": "✅ Аудио тайёр!",
        "video_failed": "❌ Боргирии видео муяссар нашуд.",
        "audio_failed": "❌ Гирифтани аудио муяссар нашуд.",
        "video_too_large": "❌ Видео хеле калон аст (>50MB). Telegram фиристани чунин файлҳоро иҷозат намедиҳад.",
        "audio_too_large": "❌ Аудио хеле калон аст (>50MB).",
        "error_occurred": "❌ Ҳангоми боргирӣ хато рух дод. Истиноди дигарро санҷед.",
        "change_language_btn": "🌐 Забон",
        "menu_title": "🏠 <b>Менюи асосӣ</b>\n\nАмалеро интихоб кунед:",
        "menu_download_video": "📥 Боргирии видео",
        "menu_profile": "👤 Кабинети шахсӣ",
        "menu_language": "🌐 Забон",
        "send_link_prompt": "📥 <b>Истинод ба видеоро фиристед</b>\n\nИстинод аз TikTok, YouTube ё Instagram — ман видео бе аломати обӣ бор мекунам.",
        "profile_title": "👤 <b>Кабинети шахсӣ</b>",
        "profile_user_id": "🆔 ID",
        "profile_name": "👤 Ном",
        "profile_registered": "📅 Сабти ном",
        "profile_subscription": "⭐ Обуна",
        "profile_sub_free": "Ройгон",
        "profile_sub_premium": "💎 Премиум",
        "profile_sub_until": "Муҳлати",
        "profile_sub_none": "Не",
        "profile_downloads": "📊 Ҳамаи боргириҳо",
        "profile_balance": "💰 Баланс",
        "back_btn": "🔙 Бозгашт",
        "premium_feature": "⭐ <b>Ин функсияи премиум аст</b>\n\nТанҳо барои обуначиёни Premium дастрас аст. Барои гирифтани боргирии номаҳдуд, коркарди афзалиятнок ва дигар бартариҳо обуна шавед!",
        "daily_remaining": "Боргирии боқимонда: {n}/5",
        "daily_limit_reached": "❌ Лимити рӯзона тамом шуд.\n\nРӯзона 5 файлро ройгон бор кардан мумкин аст. Лимит ҳар рӯз соати 00:00 UTC нав мешавад.\n\n⭐ <b>Premium харед</b> барои боргирии номаҳдуд!",
        "caption_video": "🎬 Видео тавассути @videoloadtt_bot бор шуд",
        "caption_audio": "🎵 Аудио тавассути @videoloadtt_bot бор шуд",
    },
    "uz": {
        "name": "O'zbek",
        "choose_language": "🌐 Tilni tanlang:",
        "language_changed": "✅ Til O'zbek tiliga o'zgartirildi",
        "welcome": (
            "👋 <b>Salom, {name}! Men suv belgisiz video yuklovchi botman.</b>\n\n"
            "Menga shunchaki havola yubor:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "Men senga video va/yoki audio yuklab beraman!"
        ),
        "unknown_link": "❌ Men bu havolani tanimadim.\nIltimos, TikTok, YouTube yoki Instagram-dan havola yuboring.",
        "recognizing": "🔗 Videoni taniyman... Bir soniya kutib tur",
        "video_info_error": "❌ Video haqida ma'lumot olish imkoni yo'q. Havolani tekshiring.",
        "unknown_duration": "noma'lum",
        "what_to_download": "Nima yuklash kerak?",
        "video_btn": "🎬 Video",
        "audio_btn": "🎵 Audio",
        "both_btn": "📦 Video + Audio",
        "link_not_found": "❌ Havola topilmadi. Uni qayta yuboring.",
        "starting_download": "⏳ Yuklashni boshlayman... Bir necha soniya ketishi mumkin",
        "downloading_video": "📥 Videoni yuklayapman...",
        "downloading_audio": "📥 Audioni yuklayapman...",
        "sending_video": "📤 Videoni yuboryapman...",
        "sending_audio": "📤 Audioni yuboryapman...",
        "video_ready": "✅ Video tayyor!",
        "audio_ready": "✅ Audio tayyor!",
        "video_failed": "❌ Videoni yuklash imkoni yo'q.",
        "audio_failed": "❌ Audioni olish imkoni yo'q.",
        "video_too_large": "❌ Video juda katta (>50MB). Telegram bunday fayllarni yuborishga ruxsat bermaydi.",
        "audio_too_large": "❌ Audio juda katta (>50MB).",
        "error_occurred": "❌ Yuklashda xatolik yuz berdi. Boshqa havolani sinab ko'ring.",
        "change_language_btn": "🌐 Til",
        "menu_title": "🏠 <b>Bosh menyu</b>\n\nAmalni tanlang:",
        "menu_download_video": "📥 Video yuklash",
        "menu_profile": "👤 Shaxsiy kabinet",
        "menu_language": "🌐 Til",
        "send_link_prompt": "📥 <b>Video havolasini yuboring</b>\n\nTikTok, YouTube yoki Instagram havolalari — men suv belgisiz video yuklab beraman.",
        "profile_title": "👤 <b>Shaxsiy kabinet</b>",
        "profile_user_id": "🆔 ID",
        "profile_name": "👤 Ism",
        "profile_registered": "📅 Ro'yxatdan o'tgan",
        "profile_subscription": "⭐ Obuna",
        "profile_sub_free": "Bepul",
        "profile_sub_premium": "💎 Premium",
        "profile_sub_until": "Muddati",
        "profile_sub_none": "Yo'q",
        "profile_downloads": "📊 Jami yuklamalar",
        "profile_balance": "💰 Balans",
        "back_btn": "🔙 Orqaga",
        "premium_feature": "⭐ <b>Bu premium funksiya</b>\n\nFaqat Premium obunachilari uchun mavjud. Cheksiz yuklash, ustuvor ishlov berish va boshqa imtiyozlarni olish uchun obuna bo'ling!",
        "daily_remaining": "Qolgan yuklamalar: {n}/5",
        "daily_limit_reached": "❌ Kundalik limit tugadi.\n\nKuniga 5 ta faylni bepul yuklash mumkin. Limit har kuni soat 00:00 UTC da yangilanadi.\n\n⭐ <b>Premium sotib oling</b> cheksiz yuklash uchun!",
        "caption_video": "🎬 Video @videoloadtt_bot orqali yuklandi",
        "caption_audio": "🎵 Audio @videoloadtt_bot orqali yuklandi",
    },
    "ky": {
        "name": "Кыргызча",
        "choose_language": "🌐 Тилди тандаңыз:",
        "language_changed": "✅ Тил Кыргызчага өзгөртүлдү",
        "welcome": (
            "👋 <b>Салам, {name}! Мен суу белгисиз видео жүктөөчү ботмун.</b>\n\n"
            "Жөн гана мага шилтеме жөнөт:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "Мен сага видео жана/же аудио жүктөп берем!"
        ),
        "unknown_link": "❌ Мен бул шилтеме тааныбадым.\nTikTok, YouTube же Instagram-дан шилтеме жибериңиз.",
        "recognizing": "🔗 Видеону тааныймын... Бир секунд күтө тур",
        "video_info_error": "❌ Видео жөнүндө маалымат алуу мүмкүн эмес. Шилтемени текшериңиз.",
        "unknown_duration": "белгисиз",
        "what_to_download": "Эмне жүктөө керек?",
        "video_btn": "🎬 Видео",
        "audio_btn": "🎵 Аудио",
        "both_btn": "📦 Видео + Аудио",
        "link_not_found": "❌ Шилтеме табылган жок. Аны кайра жөнөтүңүз.",
        "starting_download": "⏳ Жүктөөнү баштаймын... Бир нече секунд алышы мүмкүн",
        "downloading_video": "📥 Видеону жүктөп жатам...",
        "downloading_audio": "📥 Аудиону жүктөп жатам...",
        "sending_video": "📤 Видеону жөнөтүп жатам...",
        "sending_audio": "📤 Аудиону жөнөтүп жатам...",
        "video_ready": "✅ Видео даяр!",
        "audio_ready": "✅ Аудио даяр!",
        "video_failed": "❌ Видеону жүктөө мүмкүн эмес.",
        "audio_failed": "❌ Аудиону алуу мүмкүн эмес.",
        "video_too_large": "❌ Видео өтө чоң (>50MB). Telegram мындай файлдарды жөнөтүүгө уруксат бербейт.",
        "audio_too_large": "❌ Аудио өтө чоң (>50MB).",
        "error_occurred": "❌ Жүктөөдө ката кетти. Башка шилтемени сынап көрүңүз.",
        "change_language_btn": "🌐 Тил",
        "menu_title": "🏠 <b>Башкы меню</b>\n\nАракетти тандаңыз:",
        "menu_download_video": "📥 Видео жүктөө",
        "menu_profile": "👤 Жеке кабинет",
        "menu_language": "🌐 Тил",
        "send_link_prompt": "📥 <b>Видеого шилтеме жибериңиз</b>\n\nTikTok, YouTube же Instagram шилтемелери — мен суу белгисиз видео жүктөп берем.",
        "profile_title": "👤 <b>Жеке кабинет</b>",
        "profile_user_id": "🆔 ID",
        "profile_name": "👤 Аты",
        "profile_registered": "📅 Катталган",
        "profile_subscription": "⭐ Жазылуу",
        "profile_sub_free": "Акысыз",
        "profile_sub_premium": "💎 Премиум",
        "profile_sub_until": "Мөөнөтү",
        "profile_sub_none": "Жок",
        "profile_downloads": "📊 Бардык жүктөөлөр",
        "profile_balance": "💰 Баланс",
        "back_btn": "🔙 Артка",
        "premium_feature": "⭐ <b>Бул премиум функция</b>\n\nТек Premium жазылуучуларына жеткиликтүү. Чексиз жүктөө, артыкчылыктуу иштетүү жана башка артыкчылыктарды алуу үчүн жазылыңыз!",
        "daily_remaining": "Калган жүктөөлөр: {n}/5",
        "daily_limit_reached": "❌ Күндүк лимит бүттү.\n\nКүнүнө 5 файлды акысыз жүктөөгө болот. Лимит күн сайын саат 00:00 UTC жаңыланат.\n\n⭐ <b>Premium сатып алыңыз</b> чексиз жүктөө үчүн!",
        "caption_video": "🎬 Видео @videoloadtt_bot аркылуу жүктөлдү",
        "caption_audio": "🎵 Аудио @videoloadtt_bot аркылуу жүктөлдү",
    },
    "en": {
        "name": "English",
        "choose_language": "🌐 Choose language:",
        "language_changed": "✅ Language changed to English",
        "welcome": (
            "👋 <b>Hi, {name}!</b>\n\n"
            "<b>I'm a bot for downloading videos without watermarks.</b>\n\n"
            "Just send me a video link from:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "I'll download the video and/or audio for you!"
        ),
        "unknown_link": "❌ I don't recognize this link.\nPlease send a link to a video from TikTok, YouTube or Instagram.",
        "recognizing": "🔗 Recognizing video... Wait a second",
        "video_info_error": "❌ Could not get video info. Check the link.",
        "unknown_duration": "unknown",
        "what_to_download": "What to download?",
        "video_btn": "🎬 Video",
        "audio_btn": "🎵 Audio",
        "both_btn": "📦 Video + Audio",
        "link_not_found": "❌ Link not found. Send it again.",
        "starting_download": "⏳ Starting download... This may take a few seconds",
        "downloading_video": "📥 Downloading video...",
        "downloading_audio": "📥 Downloading audio...",
        "sending_video": "📤 Sending video...",
        "sending_audio": "📤 Sending audio...",
        "video_ready": "✅ Video ready!",
        "audio_ready": "✅ Audio ready!",
        "video_failed": "❌ Could not download video.",
        "audio_failed": "❌ Could not extract audio.",
        "video_too_large": "❌ Video is too large (>50MB). Telegram does not allow sending such files.",
        "audio_too_large": "❌ Audio is too large (>50MB).",
        "error_occurred": "❌ An error occurred while downloading. Try another link.",
        "change_language_btn": "🌐 Language",
        "menu_title": "🏠 <b>Main Menu</b>\n\nChoose an action:",
        "menu_download_video": "📥 Download video",
        "menu_profile": "👤 My Account",
        "menu_language": "🌐 Language",
        "send_link_prompt": "📥 <b>Send a video link</b>\n\nLinks from TikTok, YouTube or Instagram — I'll download the video without a watermark.",
        "profile_title": "👤 <b>My Account</b>",
        "profile_user_id": "🆔 ID",
        "profile_name": "👤 Name",
        "profile_registered": "📅 Registered",
        "profile_subscription": "⭐ Subscription",
        "profile_sub_free": "Free",
        "profile_sub_premium": "💎 Premium",
        "profile_sub_until": "Valid until",
        "profile_sub_none": "None",
        "profile_downloads": "📊 Total downloads",
        "profile_balance": "💰 Balance",
        "back_btn": "🔙 Back",
        "premium_feature": "⭐ <b>This is a premium feature</b>\n\nAvailable only for Premium subscribers. Subscribe to get unlimited downloads, priority processing and more!",
        "daily_remaining": "Remaining downloads: {n}/5",
        "daily_limit_reached": "❌ Daily limit reached.\n\nFree users can download 5 files per day. The limit resets every day at 00:00 UTC.\n\n⭐ <b>Get Premium</b> for unlimited downloads!",
        "caption_video": "🎬 Video downloaded via @videoloadtt_bot",
        "caption_audio": "🎵 Audio downloaded via @videoloadtt_bot",
    },
    "ar": {
        "name": "العربية",
        "choose_language": "🌐 اختر اللغة:",
        "language_changed": "✅ تم تغيير اللغة إلى العربية",
        "welcome": (
            "👋 <b>مرحباً {name}! أنا بوت تحميل الفيديو بدون علامة مائية.</b>\n\n"
            "فقط أرسل لي رابط فيديو من:\n"
            "🎵 TikTok\n"
            "▶️ YouTube\n"
            "📸 Instagram\n"
            "📌 Pinterest\n\n"
            "سأقوم بتحميل الفيديو و/أو الصوت لك!"
        ),
        "unknown_link": "❌ لم أتعرف على هذا الرابط.\nالرجاء إرسال رابط فيديو من TikTok أو YouTube أو Instagram.",
        "recognizing": "🔗 جارٍ التعرف على الفيديو... انتظر لحظة",
        "video_info_error": "❌ تعذر الحصول على معلومات الفيديو. تحقق من الرابط.",
        "unknown_duration": "غير معروف",
        "what_to_download": "ماذا تريد تحميل؟",
        "video_btn": "🎬 فيديو",
        "audio_btn": "🎵 صوت",
        "both_btn": "📦 فيديو + صوت",
        "link_not_found": "❌ الرابط غير موجود. أرسله مرة أخرى.",
        "starting_download": "⏳ جارٍ بدء التحميل... قد يستغرق بضع ثوانٍ",
        "downloading_video": "📥 جارٍ تحميل الفيديو...",
        "downloading_audio": "📥 جارٍ تحميل الصوت...",
        "sending_video": "📤 جارٍ إرسال الفيديو...",
        "sending_audio": "📤 جارٍ إرسال الصوت...",
        "video_ready": "✅ الفيديو جاهز!",
        "audio_ready": "✅ الصوت جاهز!",
        "video_failed": "❌ تعذر تحميل الفيديو.",
        "audio_failed": "❌ تعذر استخراج الصوت.",
        "video_too_large": "❌ الفيديو كبير جداً (>50MB). Telegram لا يسمح بإرسال مثل هذه الملفات.",
        "audio_too_large": "❌ الصوت كبير جداً (>50MB).",
        "error_occurred": "❌ حدث خطأ أثناء التحميل. جرب رابطاً آخر.",
        "change_language_btn": "🌐 اللغة",
        "menu_title": "🏠 <b>القائمة الرئيسية</b>\n\nاختر الإجراء:",
        "menu_download_video": "📥 تحميل فيديو",
        "menu_profile": "👤 حسابي الشخصي",
        "menu_language": "🌐 اللغة",
        "send_link_prompt": "📥 <b>أرسل رابط الفيديو</b>\n\nروابط TikTok أو YouTube أو Instagram — سأقوم بتحميل الفيديو بدون علامة مائية.",
        "profile_title": "👤 <b>حسابي الشخصي</b>",
        "profile_user_id": "🆔 المعرف",
        "profile_name": "👤 الاسم",
        "profile_registered": "📅 تاريخ التسجيل",
        "profile_subscription": "⭐ الاشتراك",
        "profile_sub_free": "مجاني",
        "profile_sub_premium": "💎 بريميوم",
        "profile_sub_until": "صالح حتى",
        "profile_sub_none": "لا يوجد",
        "profile_downloads": "📊 إجمالي التحميلات",
        "profile_balance": "💰 الرصيد",
        "back_btn": "🔙 رجوع",
        "premium_feature": "⭐ <b>هذه ميزة بريميوم</b>\n\nمتاحة فقط لمشتركي Premium. اشترك الآن للحصول على تحميل غير محدود، معالجة ذات أولوية ومزايا أخرى!",
        "daily_remaining": "التنزيلات المتبقية: {n}/5",
        "daily_limit_reached": "❌ تم استنفاد الحد اليومي.\n\nيمكن للمستخدمين المجانيين تنزيل 5 ملفات يومياً. يتم تجديد الحد يومياً عند الساعة 00:00 UTC.\n\n⭐ <b>اشترك في Premium</b> للتنزيل غير المحدود!",
        "caption_video": "🎬 تم تحميل الفيديو عبر @videoloadtt_bot",
        "caption_audio": "🎵 تم تحميل الصوت عبر @videoloadtt_bot",
    },
}

LANG_LIST = ["ru", "en", "uk", "kz", "tj", "uz", "ky", "ar"]

def t(key: str, lang: str) -> str:
    return LANGUAGES.get(lang, LANGUAGES["ru"]).get(key, LANGUAGES["ru"].get(key, key))
